services:
  db:
    image: postgres
    container_name: Infoskjerm_container
    restart: always
    environment:
      POSTGRES_USER: Infoskjerm_user
      POSTGRES_PASSWORD: cryptid-scary-orange
      POSTGRES_DB: Infoskjerm_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
