// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";
import {defineConfig} from "@prisma/config";

// let url;
// if (process.env.DATABASE_URL) {
//   url = process.env.DATABASE_URL;
// } else {
//   throw
// }
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
