import { useQuery } from "@tanstack/react-query";

export const useTQLeaderboard = () => {
  return useQuery({
    queryKey: ["TQLeaderboard"],
    queryFn: async () => {
      // Simulate an API call
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return [
        {
          users: [
            {
              image: "Druid1",
              title: "Rusty Crab",
              titleRarity: "Legendary",
              name: "John",
              guildName: "Warriors of Light",
              username: "John_Doe",
              lastname: "Doe",
              schoolClass: "1IM1",
              level: 100,
              xp: 100000,
            },
            {
              image: "Druid2",
              title: "Epic Hero",
              titleRarity: "Epic",
              name: "Jane",
              guildName: "Mages of the Arcane",
              username: "Jane_Smith",
              lastname: "Smith",
              schoolClass: "1IM2",
              level: 90,
              xp: 90000,
            },
            {
              image: "Druid3",
              title: "Rare Adventurer",
              titleRarity: "Rare",
              name: "Doe",
              guildName: "Rogues of the Shadows",
              username: "Shadow_Rogue",
              lastname: "Doe",
              schoolClass: "1IM3",
              level: 80,
              xp: 80000,
            },
            {
              image: "Druid4",
              title: "Champion",
              titleRarity: "Epic",
              name: "Mia",
              guildName: "Starlight",
              username: "Mia_Star",
              lastname: "Hansen",
              schoolClass: "1IM4",
              level: 85,
              xp: 85000,
            },
            {
              image: "Druid1",
              title: "Brave Soul",
              titleRarity: "Rare",
              name: "Lucas",
              guildName: "Ironclad",
              username: "Lucas_Iron",
              lastname: "Berg",
              schoolClass: "1IM1",
              level: 78,
              xp: 78000,
            },
            {
              image: "Druid2",
              title: "Mystic",
              titleRarity: "Epic",
              name: "Emma",
              guildName: "Moon Keepers",
              username: "Emma_Moon",
              lastname: "Olsen",
              schoolClass: "1IM2",
              level: 92,
              xp: 92000,
            },
            {
              image: "Druid3",
              title: "Blade Dancer",
              titleRarity: "Rare",
              name: "Oliver",
              guildName: "Swift Blades",
              username: "Oli_Swift",
              lastname: "Nilsen",
              schoolClass: "1IM3",
              level: 76,
              xp: 76000,
            },
            {
              image: "Druid4",
              title: "Windrunner",
              titleRarity: "Epic",
              name: "Sophia",
              guildName: "Sky Wardens",
              username: "Sophia_Sky",
              lastname: "Larsen",
              schoolClass: "1IM4",
              level: 88,
              xp: 88000,
            },
            {
              image: "Druid1",
              title: "Stoneguard",
              titleRarity: "Rare",
              name: "Noah",
              guildName: "Stone Circle",
              username: "Noah_Stone",
              lastname: "Karlsen",
              schoolClass: "1IM1",
              level: 81,
              xp: 81000,
            },
            {
              image: "Druid2",
              title: "Lightwarden",
              titleRarity: "Legendary",
              name: "Ava",
              guildName: "Lightbearers",
              username: "Ava_Light",
              lastname: "Pedersen",
              schoolClass: "1IM2",
              level: 105,
              xp: 105500,
            },
          ],
          title: "VG1",
        },
        {
          users: [
            {
              image: "Druid1",
              title: "Chosen Champion",
              titleRarity: "Legendary",
              name: "Martin",
              guildName: "Microwave Enthusiasts",
              username: "Mr_Drift",
              lastname: "Lyse",
              schoolClass: "2IT2",
              level: 101,
              xp: 101623,
            },
            {
              image: "Druid2",
              title: "Epic Hero",
              titleRarity: "Epic",
              name: "Alice",
              guildName: "Dragon Slayers",
              username: "Dragon_Lord",
              lastname: "Smith",
              schoolClass: "2IT1",
              level: 95,
              xp: 95432,
            },
            {
              image: "Druid3",
              title: "Rare Adventurer",
              titleRarity: "Rare",
              name: "Bob",
              guildName: "Shadow Hunters",
              username: "Shadow_Blade",
              lastname: "Johnson",
              schoolClass: "2MP1",
              level: 88,
              xp: 88210,
            },
            {
              image: "Druid1",
              title: "Warden",
              titleRarity: "Epic",
              name: "Carl",
              guildName: "Northwatch",
              username: "Carl_North",
              lastname: "Eriksen",
              schoolClass: "2MP1",
              level: 93,
              xp: 93200,
            },
            {
              image: "Druid2",
              title: "Seer",
              titleRarity: "Rare",
              name: "Ingrid",
              guildName: "Oracle Guild",
              username: "Ingrid_See",
              lastname: "Olsen",
              schoolClass: "2IT1",
              level: 86,
              xp: 86010,
            },
            {
              image: "Druid3",
              title: "Berserker",
              titleRarity: "Epic",
              name: "Erik",
              guildName: "Frostborn",
              username: "Erik_Frost",
              lastname: "Haugen",
              schoolClass: "2MP1",
              level: 97,
              xp: 97000,
            },
            {
              image: "Druid4",
              title: "Ranger",
              titleRarity: "Rare",
              name: "Sara",
              guildName: "Wildroot",
              username: "Sara_Wild",
              lastname: "Johansen",
              schoolClass: "2IT2",
              level: 82,
              xp: 82000,
            },
            {
              image: "Druid1",
              title: "Paladin",
              titleRarity: "Epic",
              name: "Lukas",
              guildName: "Silver Hand",
              username: "Lukas_Pal",
              lastname: "Bakken",
              schoolClass: "2IT1",
              level: 99,
              xp: 99000,
            },
            {
              image: "Druid2",
              title: "Skald",
              titleRarity: "Rare",
              name: "Nora",
              guildName: "Bardic Circle",
              username: "Nora_Bard",
              lastname: "Lie",
              schoolClass: "2MP1",
              level: 77,
              xp: 77000,
            },
            {
              image: "Druid3",
              title: "Highlord",
              titleRarity: "Legendary",
              name: "Henrik",
              guildName: "Iron Throne",
              username: "Henrik_One",
              lastname: "Aasen",
              schoolClass: "2IT2",
              level: 110,
              xp: 110500,
            },
          ],
          title: "VG2",
        },
      ];
    },
    staleTime: 1000 * 60 * 60 * 1, // 1 hour
  });
};
